const path=require('path'),assert=require('assert'),crypto=require('crypto');
require('dotenv').config({path:path.resolve(__dirname,'../.env')});
const {Sequelize}=require('sequelize');
const original=process.env.DB_NAME,testDb='quanly_cross_engine_test_'+Date.now()+'_'+crypto.randomBytes(4).toString('hex');
const safe=()=>/^quanly_cross_engine_test_[0-9]+_[a-f0-9]+$/.test(testDb)&&testDb!==original;
if(!safe())throw Error('Unsafe database');
const manager=new Sequelize('',process.env.DB_USER,process.env.DB_PASS,{host:process.env.DB_HOST||'localhost',port:Number(process.env.DB_PORT)||3306,dialect:'mysql',logging:false});
let db,server,created=false;
(async()=>{
 await manager.query('CREATE DATABASE `'+testDb+'` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');created=true;
 process.env.DB_NAME=testDb;process.env.JWT_SECRET=crypto.randomBytes(32).toString('hex');
 db=require('../src/config/database');require('../src/models');await db.sync();
 const User=require('../src/models/User'),IG=require('../src/models/InstagramAccount'),FB=require('../src/models/FacebookAccount'),Legacy=require('../src/models/FacebookFriendSuggestion'),History=require('../src/models/CrossTargetHistory'),Batch=require('../src/models/CrossTargetBatch');
 const owner=await User.create({username:'cross_engine_user',password_hash:'test-only',role:'user'}),other=await User.create({username:'cross_engine_other',password_hash:'test-only',role:'user'});
 const registry=require('../src/services/taskRegistryService').createRegistryService(db);await registry.migrate();
 const tasks=await registry.list();await registry.saveMine(owner.username,tasks.filter(row=>['NUOI_FACEBOOK','NUOI_INSTAGRAM'].includes(row.task_key)).map(row=>({task_id:row.id,enabled:true,priority:50})));
 const igs=await IG.bulkCreate(['sourceA','sourceB','sourceC','sourceD'].map(uid=>({owner_username:owner.username,uid,raw_data:'isolated',kind:'job',device_id:uid,status:'LOGIN_THANH_CONG',live_status:'live'})));
 const foreign=await IG.create({owner_username:other.username,uid:'sourceA',raw_data:'isolated',device_id:'sourceA',status:'LOGIN_THANH_CONG'});
 const fbs=await FB.bulkCreate(Array.from({length:7},(_,i)=>({owner_username:owner.username,uid:'FB_'+i,raw_data:'isolated',kind:'job',device_id:'FB_DEVICE_'+i,cookies:'test-only',status:'LOGIN_THANH_CONG',live_status:'live'})));
 await Legacy.create({owner_username:owner.username,source_account_id:fbs[0].id,source_uid:fbs[0].uid,target_account_id:fbs[1].id,target_uid:fbs[1].uid,run_id:'legacy-run',delivered_at:new Date()});
 const {spawnSync}=require('child_process');
 for(let i=0;i<2;i++){const migrated=spawnSync(process.execPath,[path.resolve(__dirname,'migrateCrossTargets.js'),'--apply'],{env:process.env,encoding:'utf8'});assert.equal(migrated.status,0,migrated.stderr);}
 assert.equal(await Legacy.count(),1);assert.equal(await History.count(),1);assert.equal(await Batch.count(),1,'Migration is idempotent');
 const settings=require('../src/services/settingsService');
 const pool=['u1','u2','u3','u4','u5','u6'];
 const scenario=(id,list=pool)=>({id,name:id,actions:{newfeed:{enabled:true,min:30,max:60},cross_follow:{enabled:true,min:2,max:3,usernames:list}}});
 await settings.saveInstagramNurtureSettings(owner.username,{active_scenario_id:'ig',scenarios:[scenario('ig'),scenario('ig-other')]});
 await settings.saveFacebookNurtureSettings(owner.username,{active_scenario_id:'fb',scenarios:[{id:'fb',name:'fb',actions:{friend_request:{enabled:true,min:3,max:3}}}]});
 const express=require('express'),app=express();app.use(express.json());app.use('/api/settings',require('../src/middleware/jwtAuth'),require('../src/routes/settings'));app.use('/api/instagram',require('../src/routes/instagram'));app.use('/api/facebook',require('../src/routes/facebook'));app.use('/api/device',require('../src/routes/device'));app.use('/api/machine-api-configs',require('../src/routes/machineApiConfigs'));app.use((err,req,res,next)=>res.status(err.statusCode||500).json({success:false,message:err.message}));
 let base;
 const listen=async()=>{server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));base='http://127.0.0.1:'+server.address().port;};await listen();
 const post=async(url,body,who=owner.username)=>{const res=await fetch(base+url,{method:'POST',headers:{'Content-Type':'application/json','x-api-key':who},body:JSON.stringify(body)});return{status:res.status,data:await res.json()};};
 const ig=async(source,key,count=3,id='ig')=>{const res=await post('/api/instagram/nurture/targets',{source_account_id:source.id,scenario_id:id,request_id:key,count});assert.equal(res.status,200,JSON.stringify(res.data));return res.data.data;};
 const fb=async(source,key)=>{const res=await post('/api/facebook/nurture/targets',{source_account_id:source.id,scenario_id:'fb',request_id:key});assert.equal(res.status,200,JSON.stringify(res.data));return res.data.data;};
 const [a,b]=await Promise.all([ig(igs[0],'concurrent-a'),ig(igs[0],'concurrent-b')]);assert.equal(a.cycle_id,1);assert.equal(b.cycle_id,1);assert.equal(new Set([...a.targets,...b.targets]).size,6,'Concurrent batches cannot overlap');
 assert.deepEqual((await ig(igs[0],'concurrent-a')).targets,a.targets,'Same request retries same batch after exhausted pool');
 const cycle2=await ig(igs[0],'next-cycle');assert.equal(cycle2.cycle_id,2);assert.equal(cycle2.targets.length,3);
 const otherSource=await ig(igs[1],'source-b');assert.equal(otherSource.cycle_id,1);assert.equal(otherSource.targets.length,3);
 const independent=await ig(igs[0],'other-scenario',3,'ig-other');assert.equal(independent.cycle_id,1);assert.equal(independent.targets.length,3);
 const first=await ig(igs[2],'pool-first',2);
 await settings.saveInstagramNurtureSettings(owner.username,{scenarios:[scenario('ig',[...pool,'u7','u8']),scenario('ig-other')]});
 const added=await ig(igs[2],'pool-added',3);assert.equal(added.cycle_id,1);assert.equal(added.available_count,6);assert(!added.targets.some(target=>first.targets.includes(target)));
 const used=new Set([...first.targets,...added.targets]);const removed=[...pool,'u7','u8'].find(target=>!used.has(target));
 await settings.saveInstagramNurtureSettings(owner.username,{scenarios:[scenario('ig',[...pool,'u7','u8'].filter(target=>target!==removed)),scenario('ig-other')]});
 const tail=await ig(igs[2],'tail');assert.equal(tail.cycle_id,1);assert.equal(tail.targets.length,2,'Short tail does not mix cycles');assert(!tail.targets.includes(removed));
 const newCycle=await ig(igs[2],'tail-next');assert.equal(newCycle.cycle_id,2);
 await igs[0].update({device_id:'MOVED_DEVICE'});assert.deepEqual((await ig(igs[0],'next-cycle')).targets,cycle2.targets,'History independent of device');
 const report=await post('/api/instagram/nurture/targets/report',{source_account_id:igs[1].id,scenario_id:'ig',request_id:'source-b',results:otherSource.targets.map((target,i)=>({target,status:i===1?'FAILED':'SUCCESS'}))});assert.equal(report.status,200);
 const afterReport=await ig(igs[1],'after-failed');assert.equal(afterReport.cycle_id,1);assert(!afterReport.targets.some(target=>otherSource.targets.includes(target)),'FAILED stays used');
 assert.equal((await post('/api/instagram/nurture/targets/report',{source_account_id:igs[1].id,scenario_id:'ig',request_id:'source-b',results:[{target:'never-issued',status:'SUCCESS'}]})).status,400);
 assert.equal((await post('/api/instagram/nurture/targets',{source_account_id:foreign.id,scenario_id:'ig',request_id:'spoof',count:2,owner_username:other.username})).status,404);
 const [sameA,sameB]=await Promise.all([ig(igs[3],'same-key'),ig(igs[3],'same-key')]);assert.deepEqual(sameA.targets,sameB.targets);assert.equal(await Batch.count({where:{platform:'INSTAGRAM',source_account_id:igs[3].id,request_id:'same-key'}}),1);
 const fb1=await fb(fbs[0],'fb1');assert.equal(fb1.uids.length,3);assert(!fb1.uids.includes(fbs[1].uid),'Migrated target remains used');
 const fbTail=await fb(fbs[0],'fb2');assert.equal(fbTail.uids.length,2);assert(!fbTail.uids.some(uid=>fb1.uids.includes(uid)));assert.equal(fbTail.cycle_id,1);
 assert.equal((await fb(fbs[0],'fb3')).cycle_id,2);assert.deepEqual((await fb(fbs[0],'legacy-run')).uids,[fbs[1].uid],'Legacy retry preserved');
 const [fbA,fbB]=await Promise.all([fb(fbs[2],'fb-race-a'),fb(fbs[2],'fb-race-b')]);assert.equal(new Set([...fbA.uids,...fbB.uids]).size,6);
 assert.equal((await fb(fbs[3],'independent-fb')).cycle_id,1);
 const childSource = `const db=require('./src/config/database');const {reserveTargets}=require('./src/services/crossTargetService');reserveTargets({owner:'cross_engine_user',platform:'INSTAGRAM',sourceAccountId:${igs[3].id},scenarioId:'ig',requestId:'same-key',action:{enabled:true,min:2,max:3},requestedCount:3,getPool:async()=>[]}).then(batch=>console.log(JSON.stringify(batch.targets))).catch(()=>process.exitCode=1).finally(()=>db.close());`;
 const restarted=spawnSync(process.execPath,['-e',childSource],{cwd:path.resolve(__dirname,'..'),env:process.env,encoding:'utf8'});assert.equal(restarted.status,0,restarted.stderr);assert.deepEqual(JSON.parse(restarted.stdout.trim()),sameA.targets,'New Node process reads persistent history/batch');
 await new Promise(resolve=>server.close(resolve));await listen();assert.deepEqual((await ig(igs[3],'same-key')).targets,sameA.targets,'Persistence across HTTP restart');
 const legacyIg=await post('/api/instagram/nurture/get-account',{device_id:'sourceD',request_id:'legacy-ig',count:2});assert.equal(legacyIg.status,200);assert.equal(legacyIg.data.data.scenario.actions.cross_follow.usernames.length,2);
 const dispatcher=await post('/api/device/next-task',{device_id:'sourceD',capabilities:['NUOI_INSTAGRAM'],request_id:'dispatch',count:2});assert.equal(dispatcher.status,200);assert.equal(dispatcher.data.task.data.scenario.actions.cross_follow.usernames.length,2);
 const resumed=await post('/api/device/next-task',{device_id:'sourceD',capabilities:['NUOI_INSTAGRAM'],request_id:'dispatch',count:2});assert.equal(resumed.data.task.id,dispatcher.data.task.id);assert.deepEqual(resumed.data.task.data.scenario.actions.cross_follow.targets,dispatcher.data.task.data.scenario.actions.cross_follow.targets);
 const legacyFb=await post('/api/facebook/nurture/get-account',{device_id:fbs[4].device_id});assert.equal(legacyFb.status,200);assert.equal(legacyFb.data.data.friend_candidates.length,3);assert.equal(legacyFb.data.data.scenario.actions.friend_request.uids.length,3);
 // Database rejects duplicate source/target/cycle even if a caller bypasses the engine.
 const row=await History.findOne({where:{platform:'INSTAGRAM',source_account_id:igs[3].id}});const duplicate=row.toJSON();delete duplicate.id;
 await assert.rejects(()=>History.create(duplicate),err=>err.name==='SequelizeUniqueConstraintError');
 const {reserveTargets}=require('../src/services/crossTargetService');
 const deletedPool=await reserveTargets({owner:owner.username,platform:'INSTAGRAM',sourceAccountId:igs[1].id,scenarioId:'ig',requestId:'deleted-pool',action:{enabled:true,min:2,max:3},requestedCount:3,getPool:async()=>[]});assert.equal(deletedPool.targets.length,0);assert.equal(deletedPool.cycle_id,1,'Deleting entire pool does not reset cycle');
 await registry.saveMine(other.username,[{task_id:tasks.find(row=>row.task_key==='NUOI_INSTAGRAM').id,enabled:true,priority:50}]);
 await settings.saveInstagramNurtureSettings(other.username,{scenarios:[scenario('ig')]});
 const ownOther=await post('/api/instagram/nurture/targets',{source_account_id:foreign.id,scenario_id:'ig',request_id:'owner-isolated',count:3},other.username);assert.equal(ownOther.status,200);assert.equal(ownOther.data.data.cycle_id,1);
 for(const target of fbs.slice(1))await target.update({live_status:'die'});
 const emptyFb=await fb(fbs[0],'empty-pool');assert.equal(emptyFb.uids.length,0);assert.equal(emptyFb.cycle_id,2);
 const emptyScenario={id:'empty',name:'empty',actions:{cross_follow:{enabled:false,min:0,max:0,usernames:[]}}};await settings.saveInstagramNurtureSettings(owner.username,{scenarios:[emptyScenario]});
 const empty=await ig(igs[0],'off-empty',0,'empty');assert.equal(empty.targets.length,0);assert.equal(empty.cycle_id,null);
 console.log('CROSS_TARGET_ENGINE_OK: concurrency/distinct and identical keys, retries, tail/cycle reset, pool edits, FAILED, source/scenario/owner/device isolation, DB uniqueness, legacy migration twice, persistence, legacy FB/IG and dispatcher APIs');
})().catch(err=>{console.error(err.stack);process.exitCode=1;}).finally(async()=>{if(server)await new Promise(resolve=>server.close(resolve));if(db)await db.close();if(created&&safe())await manager.query('DROP DATABASE `'+testDb+'`');await manager.close();});
