const path=require('path'),assert=require('assert'),crypto=require('crypto');
require('dotenv').config({path:path.resolve(__dirname,'../.env')});
const {Sequelize}=require('sequelize');
const original=process.env.DB_NAME,name='quanly_device_test_'+Date.now()+'_'+crypto.randomBytes(4).toString('hex');
const manager=new Sequelize('',process.env.DB_USER,process.env.DB_PASS,{host:process.env.DB_HOST||'localhost',port:Number(process.env.DB_PORT)||3306,dialect:'mysql',logging:false});
let db,server,browser,created=false;
(async()=>{
 assert(/^quanly_device_test_\d+_[a-f0-9]+$/.test(name)&&name!==original);
 await manager.query('CREATE DATABASE `'+name+'` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');created=true;process.env.DB_NAME=name;
 db=require('../src/config/database');require('../src/config/logger').silent=true;require('../src/models');await db.sync();
 const User=require('../src/models/User'),Device=require('../src/models/DashboardDevice'),FB=require('../src/models/FacebookAccount');
 const registry=require('../src/services/taskRegistryService').createRegistryService(db);await registry.migrate();
 const a=await User.create({username:'device_a',password_hash:'isolated-test',role:'user'}),b=await User.create({username:'device_b',password_hash:'isolated-test',role:'admin'});
 const {ensureDevice}=require('../src/services/deviceRegistrationService');
 const {classifyDevice,paginateDevices}=require('../src/services/deviceStatusService');
 const {offlineTimeoutSeconds}=require('../src/config/devices');const now=Date.now();
 assert.equal(classifyDevice({last_seen:new Date(now),reported_status:'RUNNING'},now),'RUNNING');
 assert.equal(classifyDevice({last_seen:new Date(now),reported_status:'IDLE',current_uid:'previous-account'},now),'IDLE');
 assert.equal(classifyDevice({last_seen:new Date(now-(offlineTimeoutSeconds+1)*1000),reported_status:'RUNNING'},now),'OFFLINE');
 assert.equal(classifyDevice({last_seen:new Date(now-offlineTimeoutSeconds*1000)},now),'IDLE');
 const express=require('express'),app=express();app.use(express.json());
 app.use('/api/device',require('../src/routes/device'));
 const jwt=require('jsonwebtoken');process.env.JWT_SECRET=crypto.randomBytes(32).toString('hex');
 app.use('/api/dashboard',require('../src/middleware/jwtAuth'),require('../src/routes/dashboard'));
 app.use((err,req,res,next)=>res.status(err.statusCode||500).json({success:false,message:err.message}));
 server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;
 const api=async(user,url,body)=>{const response=await fetch(base+url,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...(body?{'x-api-key':user.username}:{Authorization:'Bearer '+jwt.sign({id:user.id,username:user.username,role:user.role},process.env.JWT_SECRET)})},...(body?{body:JSON.stringify(body)}:{})});return {status:response.status,data:await response.json()};};
 const heartbeat=(device,extra={})=>api(a,'/api/device/heartbeat',{device_id:device,...extra});
 assert.equal((await heartbeat('A',{status:'RUNNING',current_task:'PAGE_JOB'})).status,200);
 await heartbeat('B');await heartbeat('C');await Device.update({last_seen:new Date(now-(offlineTimeoutSeconds+1)*1000)},{where:{owner_username:a.username,device_id:'C'}});
 let result=await api(a,'/api/dashboard/summary');assert.equal(result.status,200,JSON.stringify(result.data));
 assert.deepEqual(result.data.data.devices.summary,{total:3,running:1,idle:1,offline:1,online:2});
 let filtered=await api(a,'/api/dashboard/summary?device_status=OFFLINE');assert.equal(filtered.data.data.devices.filtered_total,1);assert.equal(filtered.data.data.devices.rows[0].device_id,'C');
 await heartbeat('A',{status:'IDLE',current_uid:'old-account'});result=await api(a,'/api/dashboard/summary');assert.equal(result.data.data.devices.summary.idle,2);
 await Device.update({last_seen:new Date(now-(offlineTimeoutSeconds+1)*1000)},{where:{owner_username:a.username,device_id:'A'}});
 assert.equal((await api(a,'/api/dashboard/summary')).data.data.devices.summary.offline,2);
 await heartbeat('A');await heartbeat('C');assert.equal((await api(a,'/api/dashboard/summary')).data.data.devices.summary.idle,3);
 // Active task takes precedence over an IDLE heartbeat without task_id.
 const Run=require('../src/models/DeviceTaskRun');
 const run=await Run.create({owner_username:a.username,device_id:'A',task_type:'PAGE_JOB',entity_type:'FACEBOOK_PAGE_JOB',entity_id:123,locked_by:'A',locked_at:new Date()});
 await heartbeat('A',{status:'IDLE'});assert.equal((await api(a,'/api/dashboard/summary')).data.data.devices.summary.running,1);
 assert.equal((await api(a,'/api/device/task/report',{task_id:run.id})).status,200);
 assert.equal((await api(a,'/api/dashboard/summary')).data.data.devices.summary.idle,3);
 // Account.updated_at is not a device heartbeat. No registration record remains offline.
 await FB.create({owner_username:b.username,kind:'job',uid:'synthetic_legacy',raw_data:'isolated-test',device_id:'LEGACY_ONLY',status:'LOGIN_THANH_CONG'});
 const own=await require('../src/services/dashboardService').getDevices(b.username);assert.equal(own.rows[0].status,'OFFLINE');
 await ensureDevice(b.username,'LEGACY_ONLY');assert.equal((await require('../src/services/dashboardService').getDevices(b.username)).rows[0].status,'IDLE');
 // 999 known devices followed by a simultaneous attempt at the last slot.
 await Device.bulkCreate(Array.from({length:996},(_,i)=>({owner_username:a.username,device_id:'LOAD_'+String(i).padStart(4,'0'),device_name:i===995?'Find across pages':'Load '+i,reported_status:i%2?'IDLE':'RUNNING',current_task:i%2?null:'PAGE_JOB',last_seen:new Date()})));
 const raced=await Promise.all(['LAST_1','LAST_2'].map(id=>heartbeat(id)));assert.deepEqual(raced.map(r=>r.status).sort(),[200,409]);assert.equal(raced.find(r=>r.status===409).data.message,'DEVICE_LIMIT_REACHED');
 assert.equal((await heartbeat('1001')).status,409);assert.equal((await api(a,'/api/device/next-task',{device_id:'1001'})).status,409);assert.equal((await heartbeat('B')).status,200);
 result=await api(a,'/api/dashboard/summary');let data=result.data.data.devices;
 assert.equal(data.summary.total,1000);assert.equal(data.capacity,1000);assert.equal(data.rows.length,50);assert.equal(data.summary.total,data.summary.running+data.summary.idle+data.summary.offline);
 const last=await api(a,'/api/dashboard/summary?page=20&page_size=50');assert.equal(last.data.data.devices.rows.length,50);assert.equal(last.data.data.devices.page,20);
 const found=await api(a,'/api/dashboard/summary?device_search=Find%20across%20pages');assert.equal(found.data.data.devices.filtered_total,1);assert.equal(found.data.data.devices.rows[0].device_id,'LOAD_0995');
 const running=await api(a,'/api/dashboard/summary?device_status=RUNNING&page_size=100');assert.equal(running.data.data.devices.filtered_total,data.summary.running);assert(running.data.data.devices.rows.every(row=>row.status==='RUNNING'));
 const task=await api(a,'/api/dashboard/summary?device_task=PAGE_JOB');assert.equal(task.data.data.devices.filtered_total,data.summary.running);
 // Per-user capacity and owner isolation; admin dashboard is also scoped to its own devices.
 assert.equal((await api(b,'/api/device/heartbeat',{device_id:'OTHER_OWNER'})).status,200);
 const system=await api(b,'/api/dashboard/summary');assert.equal(system.data.data.devices.summary.total,2);assert.equal(system.data.data.devices.rows.length,2);
 assert((await api(a,'/api/dashboard/summary?device_search=OTHER_OWNER')).data.data.devices.filtered_total===0);
 assert.equal(paginateDevices([{status:'IDLE'}],{page:999}).page,1);
 if(process.argv.includes('--ui')){
  const fs=require('fs'),esbuild=require('../../frontend/node_modules/esbuild');
  const bundle=esbuild.buildSync({stdin:{contents:"import React from 'react';import{createRoot}from'react-dom/client';import App from './App';import './index.css';createRoot(document.getElementById('root')).render(<App/>);",resolveDir:path.resolve(__dirname,'../../frontend/src'),loader:'jsx'},bundle:true,write:false,outfile:'preview.js',jsx:'automatic',format:'iife',define:{'import.meta.env.VITE_API_BASE_URL':'undefined'}});
  app.get('/preview.js',(req,res)=>res.type('js').send(bundle.outputFiles.find(f=>f.path.endsWith('.js')).text));
  app.get('/preview.css',(req,res)=>res.type('css').send(bundle.outputFiles.find(f=>f.path.endsWith('.css')).text));
  app.use('/assets',express.static(path.resolve(__dirname,'../../frontend/public/assets')));
  assert.equal((await fetch(base+'/assets/dk-favicon-c3f2afce.png')).status,200);
  app.get('/api/stats',(req,res)=>res.json({success:true,data:{}}));
  const html=fs.readFileSync(path.resolve(__dirname,'../../frontend/index.html'),'utf8').replace('<script type="module" src="/src/main.jsx"></script>','<link rel="stylesheet" href="/preview.css"><script src="/preview.js"></script>');
  app.get(['/login','/dashboard'],(req,res)=>res.send(html));
  const {Builder,By,logging}=require('selenium-webdriver'),chrome=require('selenium-webdriver/chrome');
  const prefs=new logging.Preferences();prefs.setLevel(logging.Type.BROWSER,logging.Level.SEVERE);
  browser=await new Builder().forBrowser('chrome').setChromeOptions(new chrome.Options().addArguments('--headless=new','--window-size=1366,900')).setChromeService(new chrome.ServiceBuilder(path.join(process.env.USERPROFILE,'.cache/selenium/chromedriver/win64/154.0.8037.92/chromedriver.exe'))).setLoggingPrefs(prefs).build();
  const wait=script=>browser.wait(()=>browser.executeScript(script),15000);
  await browser.get(base+'/login');await wait('return !!document.querySelector("h1")');
  assert.equal(await browser.getTitle(),'Qu\u1ea3n l\u00fd t\u00e0i nguy\u00ean MMO');
  assert.equal(await browser.findElement(By.css('h1')).getText(),'MMO Manager');
  assert(await browser.executeScript('return [...document.images].some(img=>img.complete&&img.naturalWidth>0&&img.alt==="DK")'));
  await browser.executeScript('localStorage.setItem("tiktok_admin_token",arguments[0]);localStorage.setItem("tiktok_admin_user",arguments[1]);localStorage.setItem("tiktok_admin_role","user");',jwt.sign({id:a.id,username:a.username,role:a.role},process.env.JWT_SECRET,{expiresIn:'1h'}),a.username);
  await browser.get(base+'/dashboard');await wait('return document.querySelectorAll(".dashboard-device-row").length===50');
  assert.equal((await browser.findElements(By.css('a[href="/export"]'))).length,0);
  assert.equal(await browser.findElement(By.css('.sidebar-logo h2')).getText(),'MMO Manager');
  assert((await browser.findElement(By.css('.dashboard-device-scope')).getText()).includes('1.000'));
  const before=await browser.executeScript('return document.querySelector(".dashboard-device-row td:nth-child(2)").textContent');
  await browser.findElement(By.css('.dashboard-pagination button:last-child')).click();
  await wait('return document.querySelector(".dashboard-device-row td").textContent==="51"');
  assert.notEqual(await browser.executeScript('return document.querySelector(".dashboard-device-row td:nth-child(2)").textContent'),before);
  await browser.findElement(By.css('.dashboard-search input')).sendKeys('Find across pages');
  await wait('return document.querySelectorAll(".dashboard-device-row").length===1&&document.querySelector(".dashboard-device-row").textContent.includes("Find across pages")');
  await browser.findElement(By.css('.dashboard-search button')).click();await wait('return document.querySelectorAll(".dashboard-device-row").length===50');
  await browser.findElement(By.css('.dashboard-status-filters button:nth-child(2)')).click();
  await wait('return document.querySelectorAll(".dashboard-device-row").length>0&&[...document.querySelectorAll(".dashboard-device-row .dashboard-status")].every(el=>el.textContent==="RUNNING")');
  // Realtime uses the existing 15-second polling loop; no navigation reload.
  const documentId=await browser.executeScript('window.qaDocumentId="same-page";return document.querySelector(".dashboard-status-filters button:nth-child(2) span").textContent');
  await heartbeat('B',{status:'RUNNING',current_task:'PAGE_JOB'});
  await browser.wait(async()=>await browser.executeScript('return document.querySelector(".dashboard-status-filters button:nth-child(2) span").textContent')!==documentId,22000);
  assert.equal(await browser.executeScript('return window.qaDocumentId'),'same-page');
  await browser.sendDevToolsCommand('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
  assert(await browser.executeScript('return document.documentElement.scrollWidth<=innerWidth'),'Mobile page overflow');
  assert.equal(await browser.findElement(By.css('.mobile-brand strong')).getText(),'MMO Manager');
  assert(await browser.executeScript('return document.querySelector(".mobile-brand img").naturalWidth>0'));
  const artifacts=path.resolve(__dirname,'../../artifacts');fs.mkdirSync(artifacts,{recursive:true});await browser.executeScript('window.scrollTo(0,0)');fs.writeFileSync(path.join(artifacts,'device-dashboard-mobile.png'),await browser.takeScreenshot(),'base64');
  const errors=await browser.manage().logs().get(logging.Type.BROWSER);assert.equal(errors.length,0,'Unexpected browser error');
  console.log('DEVICE_UI_OK: real backend pagination/search/filter/polling, login/sidebar/mobile branding, supplied DK logo/favicon, no export link, no page overflow');
 }
 console.log('DEVICE_DASHBOARD_OK: status/timeout/transitions, real HTTP stats/filter/search/pages, 1000/1001/race, legacy inventory, owner isolation/admin own scope');
})().catch(err=>{console.error(err.stack);process.exitCode=1;}).finally(async()=>{
 if(browser)await browser.quit();if(server)await new Promise(resolve=>server.close(resolve));if(db)await db.close();if(created&&/^quanly_device_test_\d+_[a-f0-9]+$/.test(name)&&name!==original)await manager.query('DROP DATABASE `'+name+'`');await manager.close();
});
