const assert=require('assert');
const {createGhostInboxProvider,normalizeMessages,config,unwrap}=require('../src/services/mailProviders/GhostInboxProvider');
const {selectOtp,htmlText,parseTime}=require('../src/services/mailOtpService');
const now=Date.now(),seconds=Math.floor(now/1000);
const message=(id='fixture-id',subject='041374 is your Instagram code',body='<p>928105</p>',offset=0)=>({id,subject,sender_name:'Instagram',sender_email:'security@mail.instagram.com',timestamp:new Date(now+offset*1000).toISOString(),content:body,attachments:[[],{s:'arr'}]});
const tuple=items=>[items.map(m=>[m,{s:'arr'}]),{s:'arr'}];
const snapshot=(email,items=[])=>JSON.stringify({data:{email,messages:tuple(items),error:'',initial:false},memo:{id:'fixture-component',name:'frontend.app'},checksum:'synthetic-signature'});
const html=(email)=>'<meta name="csrf-token" content="fixture-csrf"><div wire:snapshot="'+snapshot(email).replace(/&/g,'&amp;').replace(/"/g,'&quot;')+'"></div>';
(async()=>{
 assert.equal(parseTime('2026-10-07T10:05:43+07:00'),Date.parse('2026-10-07T03:05:43Z')/1000);
 const normalized=normalizeMessages(tuple([message('a','No code','<script>123456</script><style>654321</style><p>041374</p>')]));
 assert.equal(normalized[0].id,'a');assert.equal(selectOtp(normalized,{nowSeconds:seconds}).code,'041374');
 assert(!htmlText('<script>123456</script><p>ok</p>').includes('123456'));
 assert.equal(selectOtp(normalizeMessages(tuple([message()])),{nowSeconds:seconds}).code,'041374','Subject wins over body');
 assert.equal(selectOtp(normalized,{service:'FACEBOOK',nowSeconds:seconds}),null);
 assert.equal(selectOtp(normalized,{service:'GENERIC',nowSeconds:seconds}).code,'041374');
 assert.equal(selectOtp(normalized,{minimumTime:seconds+1,nowSeconds:seconds}),null);
 assert.equal(selectOtp(normalized,{processedMessageCodes:['a'],nowSeconds:seconds}),null);
 assert.equal(selectOtp(normalizeMessages(tuple([message('old','000001','',-100),message('new','000002','',0)])),{nowSeconds:seconds}).code,'000002');
 assert.throws(()=>normalizeMessages([{}, {s:'arr'}]),e=>e.code==='GHOSTINBOX_INVALID_RESPONSE');assert.deepEqual(unwrap([[],{s:'arr'}]),[]);
 for(const env of [{GHOSTINBOX_BASE_URL:'invalid'},{GHOSTINBOX_TIMEOUT_MS:'invalid'},{GHOSTINBOX_BASE_URL:'https://example.test/path'}])assert.throws(()=>config(env));
 let clock=now,created=0,calls=[],items=[],mode='normal',transient=0;
 const settings={baseUrl:'https://ghost.example',timeoutMs:500,retryCount:2,pollIntervalMs:10000};
 const response=(status,data,type='text/html',headers={})=>({status,data,headers:{'content-type':type,...headers}});
 const http={request:async options=>{
  calls.push(options);assert.equal(options.maxRedirects,0);assert.equal(options.timeout,500);assert.equal(options.headers['User-Agent'],'QUANLY_REG-MailProvider/1.0');
  if(transient){transient--;throw Object.assign(Error('fake'),{code:'ECONNRESET'});}
  if(mode==='challenge')return response(403,'<title>Just a moment...</title>');
  if(mode==='rate')return response(429,'limited','text/plain',{'retry-after':'25'});
  if(mode==='expired')return response(419,'expired');
  if(mode==='redirect')return response(302,'','text/html',{location:settings.baseUrl+'/'});
  if(mode==='html')return response(200,'<html>ordinary unexpected HTML</html>');
  if(options.url.endsWith('/'))return response(200,'<input id="heroUser" value="fixture'+(++created)+'@gmail.com">','text/html',{'set-cookie':['ghostinbox_session=fixture-session-'+created+'; Path=/; Max-Age=7200; Secure','XSRF-TOKEN=fixture-xsrf; Path=/; Secure']});
  const n=options.headers.Cookie.match(/fixture-session-(\d+)/)?.[1],email='fixture'+n+'@gmail.com';assert(n,'Mailbox cookie required');
  if(options.url.includes('/confirm-gmail-alias'))return response(302,'','text/html',{location:settings.baseUrl+'/inbox'});
  if(options.url.endsWith('/inbox'))return response(200,html(email));
  assert(options.url.endsWith('/livewire/update'));assert.equal(options.headers['X-Livewire'],'');assert.equal(options.data._token,'fixture-csrf');const sent=JSON.parse(options.data.components[0].snapshot);assert.equal(sent.checksum,'synthetic-signature');assert.equal(sent.data.email,email);assert(options.data.components[0].calls.every(c=>c.method==='__dispatch'));
  return response(200,JSON.stringify({components:[{snapshot:snapshot(email,items),effects:{}}],assets:[]}),'application/json');
 }};
 const delays=[],p=createGhostInboxProvider({settings,http,now:()=>clock,sleep:async ms=>delays.push(ms)});
 const a=await p.createMailbox(),b=await p.createMailbox();assert.notEqual(a.providerState.cookies.ghostinbox_session.value,b.providerState.cookies.ghostinbox_session.value);
 let before=calls.length;assert.deepEqual(await p.getMessages(a),[]);assert.equal(calls.length,before,'Respect 10s polling interval');
 clock+=10001;items=[message()];before=calls.length;const messages=await p.getMessages(a);assert.equal(calls.length,before+1,'Exactly one upstream POST per normal poll');assert.equal(messages.length,1);assert.equal(p.extractOtp(messages,{nowSeconds:seconds+11}).code,'041374');assert.equal(p.getMessage(messages,'fixture-id').id,'fixture-id');
 clock+=10001;mode='challenge';before=calls.length;await assert.rejects(()=>p.getMessages(a),e=>e.code==='GHOSTINBOX_ACCESS_CHALLENGE');assert.equal(calls.length,before+1);
 mode='rate';before=calls.length;await assert.rejects(()=>p.getMessages(a),e=>e.code==='GHOSTINBOX_RATE_LIMITED');assert.equal(calls.length,before+1);assert(a.providerState.retryAfterAt>=clock+25000);await assert.rejects(()=>p.getMessages(a),e=>e.code==='GHOSTINBOX_RATE_LIMITED');assert.equal(calls.length,before+1);
 clock+=25001;mode='expired';await assert.rejects(()=>p.getMessages(a),e=>e.code==='GHOSTINBOX_SESSION_EXPIRED');
 mode='redirect';await assert.rejects(()=>p.getMessages(a),e=>e.code==='GHOSTINBOX_SESSION_EXPIRED');mode='html';await assert.rejects(()=>p.getMessages(a),e=>e.code==='GHOSTINBOX_INVALID_RESPONSE');
 mode='normal';transient=2;await p.getMessages(a);assert.deepEqual(delays,[250,500]);
 a.providerState.cookies.ghostinbox_session.expiresAt=clock-1;await assert.rejects(()=>p.getMessages(a),e=>e.code==='GHOSTINBOX_SESSION_EXPIRED');
 const install=require('../../tools/autotouch/mail'),API={};let clientCalls=0,sleeps=[];
 install(API,{getBaseUrl:()=> 'https://vps.example',getApiKey:()=> 'fixture',sleep:s=>sleeps.push(s),exec:command=>{assert(!command.includes('ghostinbox.net'));assert(command.includes('/api/mail/'));return JSON.stringify(command.includes('/new')?{success:true,provider:'GHOSTINBOX',mailbox_id:'fixture-uuid',email:'fixture@gmail.com'}:++clientCalls<3?{success:true,status:'WAITING',code:null}:{success:true,status:'RECEIVED',code:'041374'});}});
 const mail=API._Mail_New('GHOSTINBOX');assert.equal(API._Mail_GetOTP(mail.mailbox_id),'041374');assert.deepEqual(sleeps,[10,10]);
 console.log('MAIL_UNIT_OK: normalized Livewire/messages, ISO timestamps, subject/body/HTML/zero, service/old/processed filters, sessions, CSRF, challenge, expiry, retries, Retry-After, 10s polling, AutoTouch');
})().catch(e=>{console.error(e.stack);process.exitCode=1;});
