// Real dispatcher/API tests exclusively in a disposable database; never seed application DB.
const path=require('path'),assert=require('assert'),crypto=require('crypto');
require('dotenv').config({path:path.resolve(__dirname,'../.env')});
const {Sequelize,QueryTypes}=require('sequelize');
const original=process.env.DB_NAME,testDb='quanly_round_robin_test_'+Date.now()+'_'+crypto.randomBytes(4).toString('hex');
const safe=()=>/^quanly_round_robin_test_[0-9]+_[a-f0-9]+$/.test(testDb)&&testDb!==original;
const manager=new Sequelize('',process.env.DB_USER,process.env.DB_PASS,{host:process.env.DB_HOST||'localhost',port:Number(process.env.DB_PORT)||3306,dialect:'mysql',logging:false});
let db,server,browser,created=false;
(async()=>{
 assert(safe());await manager.query('CREATE DATABASE `'+testDb+'` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');created=true;
 process.env.DB_NAME=testDb;process.env.JWT_SECRET=crypto.randomBytes(32).toString('hex');
 db=require('../src/config/database');require('../src/config/logger').silent=true;require('../src/models');await db.sync();
 await db.query('CREATE TABLE facebook_page_claim_daily_stats (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,owner_username VARCHAR(100) NOT NULL,device_id VARCHAR(255) NOT NULL,stat_date DATE NOT NULL,page_count INT UNSIGNED NOT NULL DEFAULT 0,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,UNIQUE KEY uq_fb_page_claim_owner_device_date(owner_username,device_id,stat_date))');
 const User=require('../src/models/User'),FB=require('../src/models/FacebookAccount'),IG=require('../src/models/InstagramAccount'),Run=require('../src/models/DeviceTaskRun');
 const a=await User.create({username:'rr_a',password_hash:'test-only',role:'user'}),b=await User.create({username:'rr_b',password_hash:'test-only',role:'admin'});
 const registry=require('../src/services/taskRegistryService').createRegistryService(db);await registry.migrate();
 const settings=require('../src/services/settingsService'),rr=require('../src/services/roundRobinService').createRoundRobinService(db);
 const tasks=await registry.list(a.username),keys=['NUOI_FACEBOOK','NUOI_INSTAGRAM','REG_INSTAGRAM','INSTAGRAM_JOB'];
 const ids=keys.map(key=>tasks.find(t=>t.task_key===key).id),all=[...ids,...tasks.filter(t=>!keys.includes(t.task_key)).map(t=>t.id)];
 const setup=async(user,enabled=keys,order=all)=>registry.saveMine(user.username,tasks.map(t=>({task_id:t.id,enabled:enabled.includes(t.task_key),priority:t.default_priority})),order);
 const scenario={id:'rr',name:'Round robin test',actions:{newfeed:{enabled:true,min:30,max:60}}};
 for(const user of [a,b]){await settings.saveFacebookNurtureSettings(user.username,{active_scenario_id:'rr',scenarios:[scenario]});await settings.saveInstagramNurtureSettings(user.username,{active_scenario_id:'rr',scenarios:[scenario]});await setup(user);}
 const express=require('express'),jwt=require('jsonwebtoken'),app=express();app.use(express.json());
 let rejectSave=false;
 app.use('/api/task-registry',(req,res,next)=>rejectSave&&req.method==='PUT'?res.status(503).json({success:false,message:'Test save failure'}):next());
 app.use('/api/task-registry',require('../src/middleware/jwtAuth'),require('../src/routes/taskRegistry'));
 app.use('/api/device',require('../src/routes/device'));
 app.use((err,req,res,next)=>res.status(err.statusCode||500).json({success:false,message:err.message}));
 server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;
 const token=user=>jwt.sign({id:user.id,username:user.username,role:user.role},process.env.JWT_SECRET);
 const api=async(user,url,method='GET',body,device=false)=>{const response=await fetch(base+url,{method,headers:{'Content-Type':'application/json',...(device?{'x-api-key':user.username}:{Authorization:'Bearer '+token(user)})},...(body?{body:JSON.stringify(body)}:{})});return {status:response.status,data:await response.json()};};
 let sequence=0;
 const phone=async(user=a)=>{const phoneNumber=++sequence;const id='RR_PHONE_'+phoneNumber;await FB.create({owner_username:user.username,kind:'job',uid:'900000'+phoneNumber,raw_data:'isolated-test',cookies:'synthetic-test-cookie',device_id:id,status:'LOGIN_THANH_CONG',live_status:'live',login_at:new Date()});await IG.bulkCreate([0,1].map(i=>({owner_username:user.username,kind:'job',uid:'rr_ig_'+phoneNumber+'_'+i,raw_data:'isolated-test',device_id:id,status:'LOGIN_THANH_CONG',live_status:'live',login_at:new Date()})));return id;};
 const dispatch=(user,device,extra={})=>api(user,'/api/device/next-task','POST',{device_id:device,...extra},true);
 const take=async(user=a,extra={})=>{const result=await dispatch(user,await phone(user),extra);assert.equal(result.status,200);assert(result.data.task,JSON.stringify(result.data));return result.data.task;};
 const state=async(user=a)=>(await db.query('SELECT next_task_id FROM user_dispatcher_state WHERE user_id=:id',{replacements:{id:user.id},type:QueryTypes.SELECT}))[0].next_task_id;
 const cursor=async(id,user=a)=>db.query('UPDATE user_dispatcher_state SET next_task_id=:next WHERE user_id=:id',{replacements:{next:id,id:user.id}});
 await cursor(ids[0]);
 const ten=[];for(let i=0;i<10;i++)ten.push((await take()).type);assert.deepEqual(ten,Array.from({length:10},(_,i)=>keys[i%4]));
 await cursor(ids[0]);const fourPhones=await Promise.all(Array.from({length:4},()=>phone()));const four=await Promise.all(fourPhones.map(id=>dispatch(a,id)));assert(four.every(r=>r.status===200));assert.deepEqual(four.map(r=>r.data.task.type).sort(),[...keys].sort());assert.equal(new Set(four.map(r=>r.data.task.id)).size,4);
 const resumeCursor=await state();const resumed=await Promise.all([dispatch(a,fourPhones[0]),dispatch(a,fourPhones[0])]);assert(resumed.every(r=>r.data.task.id===four[0].data.task.id&&r.data.task.resumed));assert.equal(await state(),resumeCursor,'Resume does not advance');
 await cursor(ids[0]);const manyPhones=await Promise.all(Array.from({length:50},()=>phone()));const started=Date.now(),many=await Promise.all(manyPhones.map(id=>dispatch(a,id)));assert(many.every(r=>r.status===200&&r.data.task),JSON.stringify(many.find(r=>r.status!==200||!r.data.task)));
 const counts=Object.fromEntries(keys.map(key=>[key,many.filter(r=>r.data.task.type===key).length]));assert.deepEqual(counts,Object.fromEntries(keys.map((key,i)=>[key,i<2?13:12])));assert.equal(new Set(many.map(r=>r.data.task.id)).size,50);
 const beforeResume=await state();const fiftyResumes=await Promise.all(manyPhones.map(id=>dispatch(a,id)));assert(fiftyResumes.every((r,i)=>r.status===200&&r.data.task.resumed&&r.data.task.id===many[i].data.task.id));assert.equal(await state(),beforeResume,'50 simultaneous resumes neither consume extra connections nor advance cursor');
 console.log('ROUND_ROBIN_CONCURRENCY_OK: 4 and 50 simultaneous real HTTP requests; distribution '+JSON.stringify(counts)+'; elapsed_ms='+String(Date.now()-started));
 await cursor(ids[0]);await settings.saveInstagramNurtureSettings(a.username,{scenarios:[]});const skipped=[];for(let i=0;i<6;i++)skipped.push((await take()).type);assert.deepEqual(skipped,[keys[0],keys[2],keys[3],keys[0],keys[2],keys[3]]);
 await settings.saveInstagramNurtureSettings(a.username,{active_scenario_id:'rr',scenarios:[scenario]});assert.equal((await take()).type,keys[0]);assert.equal((await take()).type,keys[1],'Work comes back without reset');
 await setup(a,[keys[0],keys[2],keys[3]]);await cursor(ids[1]);assert.equal((await take()).type,keys[2],'Disabled cursor skipped');await setup(a);
 await cursor(ids[0]);assert.equal((await take(a,{capabilities:['INSTAGRAM_JOB']})).type,keys[3]);
 const noCursor=await state();const no=await dispatch(a,await phone(),{capabilities:['UNKNOWN']});assert.equal(no.data.code,0);assert.equal(no.data.task,null);assert.equal(await state(),noCursor);
 await setup(a,[]);assert.equal((await dispatch(a,await phone())).data.code,0);await setup(a);
 await cursor(ids[0]);const failPhone=await phone();Run.addHook('beforeCreate','rrFail',run=>{if(run.device_id===failPhone)throw new Error('Injected task persistence failure');});
 assert.equal((await dispatch(a,failPhone)).status,500);Run.removeHook('beforeCreate','rrFail');assert.equal(await state(),ids[0]);assert.equal((await FB.findOne({where:{device_id:failPhone,owner_username:a.username}})).nurture_status,'CHUA_NUOI','Domain reservation rolled back together with cursor');
 const retry=await dispatch(a,failPhone);assert.equal(retry.data.task.type,keys[0]);const afterClaim=await state();assert.equal((await api(a,'/api/device/task/report','POST',{task_id:retry.data.task.id,status:'FAILED',error_code:'NETWORK_ERROR'},true)).status,200);assert.equal(await state(),afterClaim,'Failure does not rewind cursor');
 const bBefore=await state(b);await take();assert.equal(await state(b),bBefore,'Separate user cursor');await cursor(ids[3],b);assert.equal((await take(b)).type,keys[3]);
 await cursor(ids[1]);const newOrder=[ids[3],ids[1],ids[0],ids[2],...all.slice(4)];assert.equal((await api(a,'/api/task-registry/order','PUT',{task_ids:newOrder,user_id:b.id})).status,200);assert.equal(await state(),ids[1]);assert.deepEqual((await registry.list(b.username)).map(t=>t.id),all,'Cannot reorder another user');
 const reordered=[];for(let i=0;i<4;i++)reordered.push((await take()).type);assert.deepEqual(reordered,[keys[1],keys[0],keys[2],keys[3]]);
 for(const invalid of [[...all,all[0]],all.slice(1),[999999,...all.slice(1)],['NUOI_FACEBOOK',...all.slice(1)]])assert.equal((await api(a,'/api/task-registry/order','PUT',{task_ids:invalid})).status,400);
 const newTask=await api(b,'/api/task-registry','POST',{task_key:'RR_NEW',name:'New registry task',platform:'COMMON',enabled:true,default_priority:500});assert.equal(newTask.status,200);const added=newTask.data.data.task;assert.equal((await registry.list(a.username)).find(t=>t.id===added.id).user_enabled,false);
 assert.equal((await api(a,'/api/task-registry','POST',{task_key:'DENIED',name:'Denied',platform:'COMMON',enabled:true})).status,403);
 await cursor(added.id);await registry.archive(added.id);assert((await take()).type,'Archived cursor normalized');
 const snapshot=async()=>({settings:await db.query('SELECT user_id,task_id,enabled,priority,dispatch_order FROM user_task_settings ORDER BY user_id,task_id',{type:QueryTypes.SELECT}),state:await db.query('SELECT user_id,next_task_id FROM user_dispatcher_state ORDER BY user_id',{type:QueryTypes.SELECT})});
 const before=await snapshot();await registry.migrate();await registry.migrate();assert.deepEqual(await snapshot(),before,'Idempotent migration preserves settings/cursor');
 // New backend process reads the persisted cursor/order, not process-local memory.
 await cursor(ids[1]);const persistentPhone=await phone();const code=`const db=require('./src/config/database');require('./src/config/logger').silent=true;require('./src/services/taskDispatcherService').getNextTask({owner:'rr_a',deviceId:${JSON.stringify(persistentPhone)},req:{api_owner_username:'rr_a',body:{},query:{}}}).then(r=>console.log(JSON.stringify(r.task.type))).finally(()=>db.close());`;
 const output=require('child_process').execFileSync(process.execPath,['-e',code],{cwd:path.resolve(__dirname,'..'),env:process.env,encoding:'utf8',timeout:30000});assert.equal(JSON.parse(output.trim()),keys[1]);assert.equal(await state(),ids[0],'Cursor survives a new Node process');
 // Page no-work must retain legacy maintenance while clearing partial reservations.
 const pageTask=tasks.find(t=>t.task_key==='PAGE_JOB'),regPage=tasks.find(t=>t.task_key==='REG_PAGE');
 const Page=require('../src/models/FacebookPageJob');
 await setup(a,['PAGE_JOB']);await cursor(pageTask.id);const completedPhone=await phone();const completedAccount=await FB.findOne({where:{device_id:completedPhone,owner_username:a.username}});
 await Page.create({owner_username:a.username,facebook_account_id:completedAccount.id,page_id:'test_completed_page',job_status:'DA_LAM',is_active:true});
 const exhausted=await dispatch(a,completedPhone);assert.equal(exhausted.data.code,0);await completedAccount.reload();assert.equal(completedAccount.status,'DA_CHAY_XONG','No-work preserves completed Page maintenance');assert.equal(completedAccount.locked_by,null);
 const emptyPagePhone=await phone();assert.equal((await dispatch(a,emptyPagePhone)).data.code,0);assert.equal((await FB.findOne({where:{device_id:emptyPagePhone,owner_username:a.username}})).locked_by,null,'Page without work leaves no orphan claim');
 const pagePhones=await Promise.all(Array.from({length:16},async()=>{const id=await phone(),account=await FB.findOne({where:{device_id:id,owner_username:a.username}});await account.update({last_page_check_at:new Date(),page_count:1,pages:JSON.stringify([{id:String(800000000+account.id),name:'Test Page',access_token:'synthetic-test-token'}])});return id;}));
 const pageClaims=await Promise.all(pagePhones.map(id=>dispatch(a,id)));assert(pageClaims.every(r=>r.status===200&&r.data.task?.type==='PAGE_JOB'),'16 cached Page requests do not escape parent connection: '+JSON.stringify(pageClaims.filter(r=>r.status!==200||r.data.task?.type!=='PAGE_JOB').map(r=>({status:r.status,message:r.data.message,has_task:r.data.has_task}))));
 const pageResumes=await Promise.all(pagePhones.map(id=>dispatch(a,id)));assert(pageResumes.every((r,i)=>r.data.task?.id===pageClaims[i].data.task.id));
 console.log('ROUND_ROBIN_PAGE_OK: 16 concurrent cached Page claims/resumes, completed-page maintenance, no orphan Page locks');
 await setup(a,['REG_PAGE']);await cursor(regPage.id);const invalidPhone=await phone();const invalidAccount=await FB.findOne({where:{device_id:invalidPhone,owner_username:a.username}});await invalidAccount.update({token:'EAATESTONLY',login_at:new Date(Date.now()-30*86400000)});
 const axios=require('axios'),get=axios.get;axios.get=async()=>({data:{error:{code:190,message:'Synthetic invalid token'}}});
 try{assert.equal((await dispatch(a,invalidPhone)).data.code,0);}finally{axios.get=get;}
 await invalidAccount.reload();assert.equal(invalidAccount.page_token_status,'die','No-work retains invalid-token maintenance');assert.equal(invalidAccount.reg_page_locked_by,null);assert.equal(await state(),regPage.id,'Failed Page reservation does not advance');
 await setup(a);await cursor(ids[0]);
 console.log('ROUND_ROBIN_API_DB_OK: exact sequence, resume, skip/return/OFF/capability/no-task, rollback, failure, owner/admin, reorder/archive, migration twice, process persistence');
 if(process.argv.includes('--ui')){
  const esbuild=require('../../frontend/node_modules/esbuild'),fs=require('fs');
  const contents=`import React from 'react';import {createRoot} from 'react-dom/client';import Tasks from './components/TaskRegistrySettings';import Toast from './components/Toast';createRoot(document.getElementById('root')).render(<div className="settings-page settings-platform-panel"><Tasks/><Toast/></div>);`;
  const bundle=esbuild.buildSync({stdin:{contents,resolveDir:path.resolve(__dirname,'../../frontend/src'),loader:'jsx'},bundle:true,write:false,jsx:'automatic',format:'iife',define:{'import.meta.env.VITE_API_BASE_URL':'undefined'}}).outputFiles[0].text;
  app.get('/preview.js',(req,res)=>res.type('js').send(bundle));app.get('/preview.css',(req,res)=>res.type('css').send(fs.readFileSync(path.resolve(__dirname,'../../frontend/src/styles/settings.css'),'utf8')));app.get('/bootstrap',(req,res)=>res.send('<html></html>'));app.get('/preview',(req,res)=>res.send('<html><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/preview.css"><div id="root"></div><script src="/preview.js"></script></html>'));
  const {Builder,By}=require('selenium-webdriver'),chrome=require('selenium-webdriver/chrome');browser=await new Builder().forBrowser('chrome').setChromeOptions(new chrome.Options().addArguments('--headless=new','--window-size=1366,900')).setChromeService(new chrome.ServiceBuilder(path.join(process.env.USERPROFILE,'.cache/selenium/chromedriver/win64/154.0.8037.92/chromedriver.exe'))).build();
  await browser.get(base+'/bootstrap');await browser.executeScript('localStorage.setItem("tiktok_admin_token",arguments[0]);',token(a));await browser.get(base+'/preview');await browser.wait(()=>browser.executeScript('return document.querySelectorAll("tbody tr").length===6'),15000);
  const uiIds=()=>browser.executeScript('return [...document.querySelectorAll("tbody tr")].map(e=>Number(e.dataset.taskId));');
  const initial=await uiIds();assert.equal((await browser.findElements(By.css('tbody input[type=number]'))).length,0,'Priority hidden from own settings');
  await browser.executeScript(`const rows=document.querySelectorAll('tbody tr'),handle=rows[0].querySelector('.task-drag-handle'),dt=new DataTransfer();handle.dispatchEvent(new DragEvent('dragstart',{bubbles:true,dataTransfer:dt}));rows[2].dispatchEvent(new DragEvent('drop',{bubbles:true,dataTransfer:dt}));`);
  const expected=[initial[1],initial[2],initial[0],...initial.slice(3)];await browser.wait(async()=>JSON.stringify((await registry.list(a.username)).map(t=>t.id))===JSON.stringify(expected),15000);await browser.wait(async()=>JSON.stringify(await uiIds())===JSON.stringify(expected),15000);
  assert((await browser.findElement(By.css('.task-order-preview')).getText()).includes('L\u1eb7p l\u1ea1i'));
  await browser.get(base+'/preview');await browser.wait(async()=>JSON.stringify(await uiIds())===JSON.stringify(expected),15000);
  rejectSave=true;await browser.findElement(By.css('tbody tr:nth-child(2) .task-order-controls button:nth-child(3)')).click();await browser.wait(()=>browser.executeScript('return !!document.querySelector(".settings-error")'),15000);assert.deepEqual(await uiIds(),expected,'Save failure restores UI order');assert.deepEqual((await registry.list(a.username)).map(t=>t.id),expected,'Failed save preserves DB');rejectSave=false;
  await browser.sendDevToolsCommand('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});assert(await browser.executeScript('return document.documentElement.scrollWidth<=innerWidth'),'Mobile no overflow');
  await browser.findElement(By.css('tbody tr:nth-child(2) .task-order-controls button:nth-child(3)')).click();await browser.wait(async()=>JSON.stringify((await registry.list(a.username)).map(t=>t.id))!==JSON.stringify(expected),15000);
  console.log('ROUND_ROBIN_UI_OK: drag/drop/save/reload, backend source of truth, priority hidden, failure rollback, preview, mobile controls/no overflow');
 }
})().catch(err=>{console.error(err.stack);process.exitCode=1;}).finally(async()=>{if(browser)await browser.quit();if(server)await new Promise(r=>server.close(r));if(db)await db.close();if(created&&safe())await manager.query('DROP DATABASE `'+testDb+'`');await manager.close();});
