// Integration tests use a uniquely named disposable database, never the configured application DB.
const path=require('path'),assert=require('assert'),crypto=require('crypto');
require('dotenv').config({path:path.resolve(__dirname,'../.env')});
const {Sequelize}=require('sequelize');
const originalDb=process.env.DB_NAME;
const testDb='quanly_registry_test_'+Date.now()+'_'+crypto.randomBytes(4).toString('hex');
if(!/^quanly_registry_test_[0-9]+_[a-f0-9]+$/.test(testDb)||testDb===originalDb)throw new Error('Unsafe test database');
const manager=new Sequelize('',process.env.DB_USER,process.env.DB_PASS,{host:process.env.DB_HOST||'localhost',port:Number(process.env.DB_PORT)||3306,dialect:'mysql',logging:false});
let db,server,created=false;
(async()=>{
 await manager.query('CREATE DATABASE `'+testDb+'` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');created=true;
 process.env.DB_NAME=testDb;process.env.JWT_SECRET=crypto.randomBytes(32).toString('hex');
 db=require('../src/config/database');
 const User=require('../src/models/User'),AppSetting=require('../src/models/AppSetting');
 await User.sync();await AppSetting.sync();
 const admin=await User.create({username:'registry_test_admin',password_hash:'test-only',role:'admin'});
 const user=await User.create({username:'registry_test_user',password_hash:'test-only',role:'user'});
 const legacy={lock_timeout_minutes:49,max_retry:7,tasks:{PAGE_JOB:{enabled:false,priority:543},INSTAGRAM_JOB:{enabled:true,priority:222}}};
 await AppSetting.create({owner_username:user.username,setting_key:'task_dispatcher',setting_value:JSON.stringify(legacy)});
 if(process.argv.includes('--legacy')){
  await db.query(`CREATE TABLE task_registry (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,task_key VARCHAR(50) NOT NULL UNIQUE,name VARCHAR(100) NOT NULL,platform VARCHAR(30) NOT NULL,description TEXT NOT NULL,enabled TINYINT(1) NOT NULL DEFAULT 1,sort_order INT NOT NULL DEFAULT 0,archived_at DATETIME NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL)`);
  await db.query(`CREATE TABLE user_tasks (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id INT UNSIGNED NOT NULL,task_id INT UNSIGNED NOT NULL,enabled TINYINT(1) NOT NULL DEFAULT 1,priority INT NOT NULL DEFAULT 0,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,UNIQUE KEY uq_user_task(user_id,task_id))`);
  const {BUILTIN_TASKS,migrateLegacyGrant}=require('../src/services/taskRegistryPolicy');
  for(const [index,task] of BUILTIN_TASKS.entries()){
   await db.query("INSERT INTO task_registry (id,task_key,name,platform,description,enabled,sort_order,created_at,updated_at) VALUES (:id,:task_key,:name,:platform,'',1,:sort_order,NOW(),NOW())",{replacements:{...task,id:index+1,sort_order:index}});
   for(const identity of [admin,user]){const setting=migrateLegacyGrant({...task,id:index+1},identity.id===user.id?legacy:{});await db.query('INSERT INTO user_tasks (user_id,task_id,enabled,priority,created_at,updated_at) VALUES (:user_id,:task_id,:enabled,:priority,NOW(),NOW())',{replacements:{user_id:identity.id,...setting}});}
  }
  await AppSetting.create({owner_username:'__system__',setting_key:'task_registry_v1',setting_value:'complete'});
 }
 const {createRegistryService}=require('../src/services/taskRegistryService');const registry=createRegistryService(db);
 assert.equal(await registry.effective(user.username),null);
 await registry.migrate();await registry.migrate();
 assert.equal((await registry.list()).length,6);
 const [grants]=await db.query('SELECT task_id,enabled,priority FROM user_task_settings WHERE user_id=:id',{replacements:{id:user.id}});assert.equal(grants.length,6);
 const effective=await registry.effective(user.username);assert.equal(effective.PAGE_JOB.enabled,false);assert.equal(effective.PAGE_JOB.priority,543);assert.equal(effective.INSTAGRAM_JOB.priority,222);
 const createdTask=await registry.create({task_key:'test_new_task',name:'Test New Task',platform:'FACEBOOK',description:'Isolated test',enabled:true});
 assert.equal(createdTask.task_key,'TEST_NEW_TASK');await assert.rejects(()=>registry.create({task_key:'TEST_NEW_TASK',name:'Duplicate',platform:'FACEBOOK',enabled:true}),err=>err.statusCode===409);
 assert.equal((await registry.list(user.username)).length,7);
 assert.equal((await registry.effective(user.username)).TEST_NEW_TASK.enabled,false);
 assert.equal((await registry.effective(user.username)).TEST_NEW_TASK.priority,50);
 const [missing]=await db.query('SELECT COUNT(*) total FROM user_task_settings WHERE task_id=:id',{replacements:{id:createdTask.id}});assert.equal(missing[0].total,0,'Creating global task must not fan out rows to users');
 await registry.saveMine(user.username,[{task_id:createdTask.id,enabled:true,priority:987}]);
 assert.equal((await registry.effective(user.username)).TEST_NEW_TASK.priority,987);
 assert.deepEqual((await registry.effective(admin.username)).TEST_NEW_TASK,{enabled:false,priority:50});
 await registry.update(createdTask.id,{enabled:false});assert.equal((await registry.effective(user.username)).TEST_NEW_TASK.enabled,false);
 await registry.update(createdTask.id,{enabled:true});assert.equal((await registry.effective(user.username)).TEST_NEW_TASK.enabled,true);
 await assert.rejects(()=>registry.update(createdTask.id,{task_key:'RENAMED'}));
 const express=require('express'),jwt=require('jsonwebtoken'),app=express();app.use(express.json());app.use('/api/task-registry',require('../src/middleware/jwtAuth'),require('../src/routes/taskRegistry'));app.use((err,req,res,next)=>res.status(500).json({success:false,message:'Test error'}));
 server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));const base='http://127.0.0.1:'+server.address().port+'/api/task-registry';
 const token=who=>jwt.sign({id:who.id,username:who.username,role:who.role},process.env.JWT_SECRET);
 const request=async(who,url='',method='GET',body)=>{const response=await fetch(base+url,{method,headers:{Authorization:'Bearer '+token(who),'Content-Type':'application/json'},...(body && method!=='GET'?{body:JSON.stringify(body)}:{})});return{status:response.status,data:response.headers.get('content-type')?.includes('application/json') ? await response.json() : null};};
 assert.equal((await request(user)).data.data.tasks.length,7);
 for(const [url,method,body] of [['','POST',{task_key:'ILLEGAL',name:'Illegal',platform:'COMMON',enabled:true}],['/'+createdTask.id,'PATCH',{enabled:false}],['/'+createdTask.id+'/archive','POST',{}]])assert.equal((await request(user,url,method,body)).status,403);
 for(const who of [user,admin])for(const [url,method] of [['/users','GET'],['/users/'+user.id+'/tasks','GET'],['/users/'+user.id+'/tasks','PUT']])assert.equal((await request(who,url,method,{tasks:[]})).status,404,'Assignment endpoints must be removed');
 assert.equal((await request(admin,'','POST',{task_key:'bad key',name:'',platform:'COMMON',enabled:true})).status,400);
 assert.equal((await request(user,'/mine','PUT',{user_id:admin.id,target_user_id:admin.id,tasks:[{task_id:createdTask.id,enabled:false,priority:-999,user_id:admin.id}]})).status,200);
 assert.deepEqual((await registry.effective(user.username)).TEST_NEW_TASK,{enabled:false,priority:-999});
 assert.deepEqual((await registry.effective(admin.username)).TEST_NEW_TASK,{enabled:false,priority:50});
 assert.equal((await request(user,'/mine','PUT',{tasks:[{task_id:grants[0].task_id,enabled:true,priority:1.5}]})).status,400);
 await registry.archive(createdTask.id);assert.equal((await registry.list(user.username)).length,6);
 await registry.migrate();
 const [retained]=await db.query('SELECT enabled,priority FROM user_task_settings WHERE user_id=:id AND task_id=:task',{replacements:{id:user.id,task:createdTask.id}});assert.equal(retained[0].priority,-999,'Rerun must not reset user settings');
 const [old]=await db.query('SELECT setting_value FROM app_settings WHERE owner_username=:owner AND setting_key=\'task_dispatcher\'',{replacements:{owner:user.username}});assert.deepEqual(JSON.parse(old[0].setting_value),legacy);
 require('../src/models'); await db.sync({force:false,alter:false});
 // This statistics table is created by production startup SQL, not a Sequelize model.
 await db.query(`CREATE TABLE facebook_page_claim_daily_stats (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,owner_username VARCHAR(100) NOT NULL,device_id VARCHAR(255) NOT NULL,stat_date DATE NOT NULL,page_count INT UNSIGNED NOT NULL DEFAULT 0,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,UNIQUE KEY uq_fb_page_claim_owner_device_date(owner_username,device_id,stat_date))`);
 app.use('/api/dashboard',require('../src/middleware/jwtAuth'),require('../src/routes/dashboard'));
 if(process.argv.includes('--ui')) {
  const esbuild=require('../../frontend/node_modules/esbuild'),fs=require('fs');
  const bundle=esbuild.buildSync({stdin:{contents:`import React,{useState,useRef,useCallback} from 'react';import {createRoot} from 'react-dom/client';import Common from './components/CommonSettingsPanel';import {SettingsSaveBar} from './components/SettingsPrimitives';import Toast from './components/Toast';function Preview(){const ref=useRef(null),[state,setState]=useState({dirty:false,saving:false});const report=useCallback(next=>setState(next),[]);const [dispatcher,setDispatcher]=useState({lock_timeout_minutes:30,max_retry:3,tasks:{}});return <div className="settings-page" style={{padding:24}}><Common registryRef={ref} onRegistryState={report} model={{taskDispatcher:dispatcher,proxies:'',concurrency:1,delayMs:0,batchSize:10}} setters={{taskDispatcher:setDispatcher}} /><SettingsSaveBar dirty={state.dirty} saving={state.saving} onDiscard={()=>ref.current.discard()} onSave={()=>ref.current.save()} /><Toast /></div>}createRoot(document.getElementById('root')).render(<Preview />);`,resolveDir:path.resolve(__dirname,'../../frontend/src'),loader:'jsx'},bundle:true,write:false,format:'iife',jsx:'automatic',define:{'import.meta.env.VITE_API_BASE_URL':'undefined'}}).outputFiles[0].text;
  const dashboardBundle=esbuild.buildSync({stdin:{contents:`import React from 'react';import {createRoot} from 'react-dom/client';import {BrowserRouter} from 'react-router-dom';import Dashboard from './pages/Dashboard';createRoot(document.getElementById('root')).render(<BrowserRouter><Dashboard /></BrowserRouter>);`,resolveDir:path.resolve(__dirname,'../../frontend/src'),loader:'jsx'},bundle:true,write:false,format:'iife',jsx:'automatic',loader:{'.css':'empty'},define:{'import.meta.env.VITE_API_BASE_URL':'undefined'}}).outputFiles[0].text;
  app.get('/dashboard-preview.js',(req,res)=>res.type('js').send(dashboardBundle));
  app.get('/dashboard-preview',(req,res)=>res.send('<html><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/registry-preview.css"><div id="root"></div><script src="/dashboard-preview.js"></script></html>'));
  app.get('/registry-preview.js',(req,res)=>res.type('js').send(bundle));
  app.get('/registry-preview.css',(req,res)=>res.type('css').send(fs.readFileSync(path.resolve(__dirname,'../../frontend/src/index.css'),'utf8')+fs.readFileSync(path.resolve(__dirname,'../../frontend/src/styles/settings.css'),'utf8')+fs.readFileSync(path.resolve(__dirname,'../../frontend/src/styles/dashboard.css'),'utf8')));
  app.get('/registry-bootstrap',(req,res)=>res.send('<html></html>'));
  app.get('/registry-preview',(req,res)=>res.send('<html><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/registry-preview.css"><div id="root"></div><script src="/registry-preview.js"></script></html>'));
  const {Builder,By,Key,logging}=require('selenium-webdriver'),chrome=require('selenium-webdriver/chrome');
  const prefs=new logging.Preferences();prefs.setLevel(logging.Type.BROWSER,logging.Level.SEVERE);
  const browser=await new Builder().forBrowser('chrome').setChromeOptions(new chrome.Options().addArguments('--headless=new','--window-size=1366,900')).setChromeService(new chrome.ServiceBuilder(path.join(process.env.USERPROFILE,'.cache/selenium/chromedriver/win64/154.0.8037.92/chromedriver.exe'))).setLoggingPrefs(prefs).build();
  const wait=script=>browser.wait(()=>browser.executeScript(script),15000);
  const preview='http://127.0.0.1:'+server.address().port+'/registry-preview';
  const clickText=async(selector,text)=>{const elements=await browser.findElements(By.css(selector));for(const el of elements)if(await el.isDisplayed()&&(await el.getText())===text)return el.click();throw new Error('Missing UI control: '+text);};
  try {
   await browser.get(preview.replace('/registry-preview','/registry-bootstrap'));await browser.executeScript('localStorage.setItem("tiktok_admin_token",arguments[0]);localStorage.setItem("tiktok_admin_user",arguments[1]);localStorage.setItem("tiktok_admin_role",arguments[2]);',token(admin),admin.username,admin.role);await browser.get(preview);
   await wait('return !!document.querySelector(".task-registry-settings")');await clickText('.settings-sub-tabs button','Điều phối tác vụ');
   await clickText('.settings-card-header button','+ Thêm tác vụ');
   const inputs=await browser.findElements(By.css('dialog input'));await inputs[0].sendKeys('Task UI isolated');await inputs[1].sendKeys('UI_TEST_TASK');await clickText('dialog footer button','Thêm tác vụ');
   await wait('return !document.querySelector("dialog")');
   assert((await registry.list()).some(task=>task.task_key==='UI_TEST_TASK'));
   const taskRow=async()=>{for(const row of await browser.findElements(By.css('tbody tr')))if((await row.getText()).includes('UI_TEST_TASK'))return row;throw new Error('New global task missing');};
   let row=await taskRow();assert.equal(await row.findElement(By.css('[role=switch]')).getAttribute('aria-checked'),'false');
   await row.findElement(By.css('[role=switch]')).click();let priority=await row.findElement(By.css('input[type=number]'));await priority.sendKeys(Key.CONTROL,'a',Key.NULL,'314');
   assert.equal((await browser.findElements(By.css('.settings-save-bar'))).length,1);
   await clickText('.settings-save-bar .primary','Lưu thay đổi');await wait('return !document.querySelector(".settings-save-bar")');
   assert.deepEqual((await registry.effective(admin.username)).UI_TEST_TASK,{enabled:true,priority:314});
   await browser.executeScript('localStorage.setItem("tiktok_admin_token",arguments[0]);localStorage.setItem("tiktok_admin_user",arguments[1]);localStorage.setItem("tiktok_admin_role",arguments[2]);',token(user),user.username,user.role);await browser.get(preview);
   await wait('return !!document.querySelector(".task-registry-settings")');await clickText('.settings-sub-tabs button','Điều phối tác vụ');
   assert.equal((await browser.findElements(By.css('.settings-card-header button'))).length,0);
   assert.equal((await browser.findElements(By.css('select'))).length,0,'No user selector or permission screen');
   row=await taskRow();assert.equal(await row.findElement(By.css('[role=switch]')).getAttribute('aria-checked'),'false');
   priority=await row.findElement(By.css('input[type=number]'));assert.equal(await priority.getAttribute('value'),'50');
   await row.findElement(By.css('[role=switch]')).click();await priority.sendKeys(Key.CONTROL,'a',Key.NULL,'725');
   assert.equal((await browser.findElements(By.css('.settings-save-bar'))).length,1);
   await clickText('.settings-save-bar .primary','Lưu thay đổi');await wait('return !document.querySelector(".settings-save-bar")');
   assert.deepEqual((await registry.effective(user.username)).UI_TEST_TASK,{enabled:true,priority:725});
   assert.deepEqual((await registry.effective(admin.username)).UI_TEST_TASK,{enabled:true,priority:314});
   await browser.sendDevToolsCommand('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});assert(await browser.executeScript('return document.documentElement.scrollWidth<=innerWidth'));
   await browser.sendDevToolsCommand('Emulation.clearDeviceMetricsOverride',{});
   const monitorTasks=await registry.list(user.username),page=monitorTasks.find(task=>task.task_key==='PAGE_JOB'),ig=monitorTasks.find(task=>task.task_key==='INSTAGRAM_JOB');
   const monitorFacebook=await require('../src/models/FacebookAccount').create({owner_username:user.username,uid:'monitor_fb',raw_data:'isolated',kind:'job',device_id:'MONITOR_FIXTURE',status:'LOGIN_THANH_CONG',live_status:'live'});
   await require('../src/models/FacebookPageJob').bulkCreate(Array.from({length:26},(_,i)=>({owner_username:user.username,facebook_account_id:monitorFacebook.id,page_id:String(800000000000+i),job_status:'CHUA_LAM',is_active:true})));
   await require('../src/models/InstagramAccount').bulkCreate([...Array.from({length:2},(_,i)=>({uid:'monitor_ready_'+i,status:'LOGIN_THANH_CONG'})),{uid:'monitor_running',status:'DANG_LAM'},...Array.from({length:6},(_,i)=>({uid:'monitor_error_'+i,status:'LOGIN_FAIL'}))].map(row=>({...row,owner_username:user.username,raw_data:'isolated',kind:'job',device_id:'MONITOR_FIXTURE',live_status:'live'})));
   assert.equal((await request(user,'/mine','PUT',{tasks:[{task_id:page.id,enabled:true,priority:100},{task_id:ig.id,enabled:true,priority:90}]})).status,200);
   await browser.get(preview.replace('/registry-preview','/dashboard-preview'));await wait('return !!document.querySelector(".dashboard-task-status")');
   const monitorRow=key=>`document.querySelector('[data-task-key="${key}"]')`;
   const label=key=>browser.executeScript(`return ${monitorRow(key)}.querySelector('.dashboard-task-status').textContent.trim()`);
   const numbers=key=>browser.executeScript(`return [...${monitorRow(key)}.querySelectorAll('td:nth-child(n+3)')].map(el=>Number(el.textContent))`);
   assert.equal(await label('PAGE_JOB'),'● Đang bật');assert.deepEqual(await numbers('PAGE_JOB'),[26,0,0]);
   assert.equal(await label('INSTAGRAM_JOB'),'● Đang bật');assert.deepEqual(await numbers('INSTAGRAM_JOB'),[2,1,6]);
   assert.equal((await browser.findElements(By.css('.dashboard-task-table [role=switch],.dashboard-task-table input'))).length,0);
   await browser.executeScript('window.monitorPageMarker="keep"');await browser.findElement(By.css('.dashboard-search input')).sendKeys('retained-filter');
   assert.equal((await request(user,'/mine','PUT',{tasks:[{task_id:page.id,enabled:false,priority:100}]})).status,200);
   await browser.wait(async()=>await label('PAGE_JOB')==='● Đang tắt',22000);
   assert.deepEqual(await numbers('PAGE_JOB'),[26,0,0]);assert.equal(await browser.executeScript('return window.monitorPageMarker'),'keep');assert.equal(await browser.findElement(By.css('.dashboard-search input')).getAttribute('value'),'retained-filter');
   const monitorNew=(await request(admin,'','POST',{task_key:'MONITOR_NEW_TASK',name:'Monitor New Task',platform:'COMMON',enabled:true})).data.data.task;
   await clickText('.dashboard-header-actions button','↻ Làm mới');await wait(`return !!${monitorRow('MONITOR_NEW_TASK')}`);
   assert.equal(await label('MONITOR_NEW_TASK'),'● Đang tắt');assert.deepEqual(await numbers('MONITOR_NEW_TASK'),[0,0,0]);
   assert.equal((await request(user,'/mine','PUT',{tasks:[{task_id:monitorNew.id,enabled:true,priority:50}]})).status,200);
   await clickText('.dashboard-header-actions button','↻ Làm mới');await browser.wait(async()=>await label('MONITOR_NEW_TASK')==='● Đang bật',15000);
   assert.deepEqual(await numbers('MONITOR_NEW_TASK'),[0,0,0]);
   for(const width of [1366,390]){await browser.sendDevToolsCommand('Emulation.setDeviceMetricsOverride',{width,height:844,deviceScaleFactor:1,mobile:width===390});assert(await browser.executeScript('return document.documentElement.scrollWidth<=innerWidth'));}
   console.log('DASHBOARD_TASK_STATUS_UI_OK: six requested cases, real settings API/polling without reload, OFF keeps READY26, ON keeps ERROR6, new global task OFF then ON, no toggle, mobile');
   const unexpected=(await browser.manage().logs().get(logging.Type.BROWSER)).filter(row=>!row.message.includes('favicon.ico')&&!row.message.includes('401'));assert.equal(unexpected.length,0,unexpected.map(row=>row.message).join(' | '));
   console.log('TASK_REGISTRY_ISOLATED_UI_OK: real API, admin adds global task; admin/user independently toggle and edit priority; default OFF/50, no user selector, own-only saves, shared Common panel/ref/one SaveBar, mobile no overflow');
  }finally{await browser.quit();}
 }
 // Exercise actual integrated registry-backed dispatcher, lock/retry/cooldown/claim code in the isolated DB.
 await registry.saveMine(user.username,(await registry.list(user.username)).map(task=>({task_id:task.id,enabled:false,priority:task.priority})));
 app.use('/api/device',require('../src/routes/device'));
 app.use('/api/settings',require('../src/middleware/jwtAuth'),require('../src/routes/settings'));
 const settingsResponse=await fetch('http://127.0.0.1:'+server.address().port+'/api/settings/task-dispatcher',{method:'PUT',headers:{Authorization:'Bearer '+token(user),'Content-Type':'application/json'},body:JSON.stringify({user_id:admin.id,lock_timeout_minutes:51,max_retry:4})});assert.equal(settingsResponse.status,200);assert.equal((await require('../src/services/settingsService').getTaskDispatcherSettings(user.username)).max_retry,4);assert.equal((await require('../src/services/settingsService').getTaskDispatcherSettings(admin.username)).max_retry,3);
 app.use('/api/facebook',require('../src/routes/facebook'));app.use('/api/instagram',require('../src/routes/instagram'));
 for(const endpoint of ['/facebook/job/get-login-success-account','/facebook/reg-page/get-account','/facebook/nurture/get-account','/instagram/job/get-login-success-account','/instagram/nurture/get-account','/instagram/reg/facebook/get-account']){const response=await fetch('http://127.0.0.1:'+server.address().port+'/api'+endpoint,{method:'POST',headers:{'x-api-key':user.username,'Content-Type':'application/json'},body:JSON.stringify({device_id:'UNASSIGNED_LEGACY_TEST',owner_username:admin.username})});assert.equal(response.status,403,'Legacy acquisition must enforce user settings: '+endpoint);}
 console.log('TASK_REGISTRY_LEGACY_API_OK: six legacy acquisition endpoints deny OFF tasks; response contracts unchanged when permitted');
 const deviceUrl='http://127.0.0.1:'+server.address().port+'/api/device/next-task';
 const deviceResponse=await fetch(deviceUrl,{method:'POST',headers:{'x-api-key':user.username,'Content-Type':'application/json'},body:JSON.stringify({device_id:'IDENTITY_TEST',owner_username:admin.username,user_id:admin.id,capabilities:['PAGE_JOB']})});
 assert.equal(deviceResponse.status,200);assert.equal((await deviceResponse.json()).has_task,false);
 const identityDevices=await require('../src/models/DashboardDevice').findAll({where:{device_id:'IDENTITY_TEST'},raw:true});assert(identityDevices.length);assert(identityDevices.every(row=>row.owner_username===user.username));
 console.log('TASK_REGISTRY_DEVICE_API_OK: real API key identity overrides client owner/user id; OFF user gets no task');
 const scopeDevice='SAME_DEVICE_TWO_OWNERS',igModel=require('../src/models/InstagramAccount');
 const scopeTask=(await registry.list()).find(task=>task.task_key==='INSTAGRAM_JOB');
 await igModel.bulkCreate([{owner_username:admin.username,uid:'scope_admin',raw_data:'isolated',kind:'job',device_id:scopeDevice,status:'LOGIN_THANH_CONG',live_status:'live'},{owner_username:user.username,uid:'scope_user',raw_data:'isolated',kind:'job',device_id:scopeDevice,status:'LOGIN_THANH_CONG',live_status:'live'}]);
 await registry.saveMine(admin.username,[{task_id:scopeTask.id,enabled:true,priority:777}]);await registry.saveMine(user.username,[{task_id:scopeTask.id,enabled:false,priority:444}]);
 const ownDeviceClaim=async(who,spoof)=>{const response=await fetch(deviceUrl,{method:'POST',headers:{'x-api-key':who.username,'Content-Type':'application/json'},body:JSON.stringify({device_id:scopeDevice,owner_username:spoof.username,user_id:spoof.id,capabilities:['INSTAGRAM_JOB']})});assert.equal(response.status,200);return response.json();};
 assert.equal((await ownDeviceClaim(user,admin)).has_task,false);
 const adminClaim=await ownDeviceClaim(admin,user);assert.equal(adminClaim.task.uid,'scope_admin');assert.equal(adminClaim.task.priority,777);
 await registry.saveMine(user.username,[{task_id:scopeTask.id,enabled:true,priority:444}]);
 const userClaim=await ownDeviceClaim(user,admin);assert.equal(userClaim.task.uid,'scope_user');assert.equal(userClaim.task.priority,444);assert.notEqual(userClaim.task.id,adminClaim.task.id);
 console.log('TASK_SETTINGS_DEVICE_OWNER_OK: same device id across owners, OFF denies user, ON uses own account/priority, spoofed owner ignored');
 const dispatcherUser=await User.create({username:'__dispatcher_test__',password_hash:'test-only',role:'user'});
 const settingsModule=require('../src/services/settingsService');
 const originalGetter=settingsModule.getTaskDispatcherSettings;
 const defaults=require('../src/services/deviceTaskTypes').DEFAULT_TASK_DISPATCHER;
 assert(Object.values((await settingsModule.getTaskDispatcherSettings(dispatcherUser.username)).tasks).every(task=>task.enabled===false));
 const dispatcher=require('../src/services/taskDispatcherService');
 const denied=await dispatcher.getNextTask({owner:dispatcherUser.username,deviceId:'UNASSIGNED_TEST',req:{api_owner_username:dispatcherUser.username,body:{},query:{}}});
 assert.equal(denied.task,null,'Unassigned user must receive no task');
 const builtinRegistry=(await registry.list()).filter(task=>defaults.tasks[task.task_key]);
 await registry.saveMine(dispatcherUser.username,builtinRegistry.map(task=>({task_id:task.id,enabled:true,priority:defaults.tasks[task.task_key].priority})));
 const Module=require('module'),fs=require('fs'),existingPath=path.resolve(__dirname,'testTaskDispatcher.js');
 const existing=fs.readFileSync(existingPath,'utf8');const moduleForTest=new Module(existingPath,module);moduleForTest.filename=existingPath;moduleForTest.paths=Module._nodeModulePaths(__dirname);
 moduleForTest._compile(existing.slice(0,existing.indexOf('main()\n  .then'))+'module.exports={main,cleanup};',existingPath);
 await moduleForTest.exports.main();await moduleForTest.exports.cleanup();
 // Dashboard registry includes new tasks for admins and all active global tasks for users.
 const dashboard=require('../src/services/dashboardService');
 await registry.create({task_key:'DASHBOARD_ZERO_TASK',name:'Dashboard Zero Task',platform:'COMMON',enabled:true});
 await require('../src/models/InstagramAccount').create({owner_username:admin.username,kind:'job',uid:'isolated_admin_account',raw_data:'isolated',device_id:'ADMIN_SCOPE',status:'LOGIN_THANH_CONG'});
 await require('../src/models/FacebookNurtureLog').create({owner_username:user.username,facebook_account_id:1,uid:'isolated_activity',device_id:'ACTIVITY_SCOPE',run_id:'unassigned_activity',status:'DA_NUOI',completed_at:new Date()});
 const adminSummary=await dashboard.getDashboardSummary(admin.username,true);
 assert.equal(adminSummary.scope,'system');assert.deepEqual(adminSummary.task_registry.map(task=>[task.task_key,task.user_enabled,task.priority]),(await registry.list(admin.username)).map(task=>[task.task_key,task.user_enabled,task.priority]));assert.equal(adminSummary.task_registry.length,(await registry.list()).length);
 assert.deepEqual(adminSummary.tasks.DASHBOARD_ZERO_TASK,{ready:0,running:0,errors:0});
 assert.equal(new Set(adminSummary.task_registry.map(task=>task.task_key)).size,adminSummary.task_registry.length);
 assert(adminSummary.accounts.instagram.total>=1);assert(adminSummary.activity.some(row=>row.owner_username===user.username && row.type==='NUOI_FB'));
 const userSummary=await dashboard.getDashboardSummary(user.username,false);
 assert.deepEqual(userSummary.task_registry.map(task=>task.task_key),(await registry.list(user.username)).map(task=>task.task_key));
 assert.equal(adminSummary.task_registry.find(task=>task.task_key==='PAGE_JOB').user_enabled,true,'Admin status must use own ON setting');
 assert.equal(userSummary.task_registry.find(task=>task.task_key==='PAGE_JOB').user_enabled,false,'User status must use own OFF setting');
 if(process.argv.includes('--ui')){assert.equal(adminSummary.tasks.page_job.ready,26);assert.equal(userSummary.tasks.page_job.ready,26);}
 assert.equal(userSummary.accounts.instagram.total,await require('../src/models/InstagramAccount').count({where:{owner_username:user.username,trashed_at:null}}));assert.equal(userSummary.activity.length,1);assert(userSummary.activity.every(row=>row.uid==='isolated_activity'),'Activity must remain owner scoped');
 console.log('TASK_REGISTRY_DASHBOARD_SCOPE_OK: system counts/history, user owner/task/activity isolation, new task zero stats, no duplicate rows');
 const igTask=builtinRegistry.find(task=>task.task_key==='INSTAGRAM_JOB');
 const pageTask=builtinRegistry.find(task=>task.task_key==='PAGE_JOB');
 const priorityDevice='MULTI_PRIORITY_TEST';
 const facebook=await require('../src/models/FacebookAccount').create({owner_username:dispatcherUser.username,uid:'priority_fb',raw_data:'isolated',kind:'job',device_id:priorityDevice,status:'LOGIN_THANH_CONG',live_status:'live'});
 await require('../src/models/FacebookPageJob').create({owner_username:dispatcherUser.username,facebook_account_id:facebook.id,page_id:'900000000001',job_status:'CHUA_LAM',is_active:true});
 await require('../src/models/InstagramAccount').create({owner_username:dispatcherUser.username,uid:'priority_ig',raw_data:'isolated',kind:'job',device_id:priorityDevice,status:'LOGIN_THANH_CONG',live_status:'live'});
 await registry.saveMine(dispatcherUser.username,[{task_id:pageTask.id,enabled:true,priority:1500},{task_id:igTask.id,enabled:true,priority:1000}]);
 const priorityClaim=await dispatcher.getNextTask({owner:dispatcherUser.username,deviceId:priorityDevice,requestedCapabilities:['PAGE_JOB','INSTAGRAM_JOB'],req:{api_owner_username:dispatcherUser.username,body:{},query:{}}});assert.equal(priorityClaim.task?.type,'PAGE_JOB','Higher priority must win when both task types have real READY data');
 console.log('TASK_SETTINGS_PRIORITY_ORDER_OK: PAGE_JOB chosen before INSTAGRAM_JOB with both READY');
 await registry.saveMine(dispatcherUser.username,[{task_id:igTask.id,enabled:false,priority:991}]);
 assert.equal((await settingsModule.getTaskDispatcherSettings(dispatcherUser.username)).tasks.INSTAGRAM_JOB.enabled,false);
 await registry.update(igTask.id,{enabled:false});await registry.saveMine(dispatcherUser.username,[{task_id:igTask.id,enabled:true,priority:991}]);
 assert.equal((await settingsModule.getTaskDispatcherSettings(dispatcherUser.username)).tasks.INSTAGRAM_JOB.enabled,false);
 await registry.update(igTask.id,{enabled:true});
 assert.equal((await settingsModule.getTaskDispatcherSettings(dispatcherUser.username)).tasks.INSTAGRAM_JOB.priority,991);
 const ig=require('../src/models/InstagramAccount'),runs=require('../src/models/DeviceTaskRun');
 await ig.create({owner_username:dispatcherUser.username,kind:'job',uid:'registry_revoke_account',raw_data:'isolated',device_id:'REVOKE_TEST',status:'LOGIN_THANH_CONG',live_status:'live',nurture_status:'CHUA_NUOI'});
 const claimed=await dispatcher.getNextTask({owner:dispatcherUser.username,deviceId:'REVOKE_TEST',requestedCapabilities:['INSTAGRAM_JOB'],req:{api_owner_username:dispatcherUser.username,body:{},query:{}}});
 assert(claimed.task);assert.equal(claimed.task.priority,991);
 await registry.saveMine(dispatcherUser.username,[{task_id:igTask.id,enabled:false,priority:991}]);
 const revokedResume=await dispatcher.getNextTask({owner:dispatcherUser.username,deviceId:'REVOKE_TEST',req:{api_owner_username:dispatcherUser.username,body:{},query:{}}});assert.equal(revokedResume.task,null);
 await require('../src/services/taskReportService').reportTask({owner:dispatcherUser.username,deviceId:'REVOKE_TEST',taskId:claimed.task.id,status:'SUCCESS',result:{job_done:1},req:{api_owner_username:dispatcherUser.username,body:{},query:{}}});
 await registry.archive(igTask.id);assert.equal((await runs.findByPk(claimed.task.id)).task_type,'INSTAGRAM_JOB','Archive must preserve run history');
 assert((await registry.list(null,true)).some(task=>task.task_key==='INSTAGRAM_JOB' && task.archived_at));
 console.log('TASK_SETTINGS_DISABLE_HISTORY_OK: priority used by claim, self-disabled running task not resumed, in-flight report accepted, archive keeps history/name/key');
 settingsModule.getTaskDispatcherSettings=originalGetter;
 console.log('TASK_REGISTRY_DISPATCHER_SANDBOX_OK: actual registry-backed dispatcher settings; default OFF denied, same-device race, two-device isolation, report success, retry, timeout release and preview lock behavior');
 console.log((process.argv.includes('--legacy')?'TASK_SETTINGS_LEGACY_UPGRADE_OK':'TASK_SETTINGS_FRESH_MIGRATION_OK'));
 console.log('TASK_REGISTRY_DB_API_OK: isolated DB; idempotent migration, old settings preserved, registry CRUD/archive, global visibility/default OFF, self-enabled/priority, owner isolation, removed assign endpoints, direct admin API 403, own timeout/retry');
})().catch(err=>{console.error('Task registry isolated test failed: '+err.stack);process.exitCode=1;}).finally(async()=>{
 if(server)await new Promise(resolve=>server.close(resolve));if(db)await db.close();
 if(created&&/^quanly_registry_test_[0-9]+_[a-f0-9]+$/.test(testDb)&&testDb!==originalDb)await manager.query('DROP DATABASE `'+testDb+'`');await manager.close();
});
